name: "LLaMA Code Review Action"
description: "Perform code reviews and comment on diffs using Databricks LLaMA 3.3 70B."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  DATABRICKS_API_TOKEN:
    description: "Databricks API token for authentication."
    required: true
  DATABRICKS_ENDPOINT_URL:
    description: "Databricks endpoint URL for the LLaMA 3.3 70B model."
    required: true
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "cpu"
  color: "blue"
