name: Code Review with LLaMA
on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Code Review
        uses: your-username/llama-code-reviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATABRICKS_API_TOKEN: ${{ secrets.DATABRICKS_API_TOKEN }}
          DATABRICKS_ENDPOINT_URL: ${{ secrets.DATABRICKS_ENDPOINT_URL }}
          exclude: "yarn.lock,dist/**"
